const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('simpmcAPI', {
    getUserLocale: () => ipcRenderer.invoke('get_user_locale'),
    getAppLocale: () => ipcRenderer.invoke('get_app_locale'),
    sendWindowControl: (action) => ipcRenderer.send('window-control', action),
    checkFirstRun: () => ipcRenderer.invoke('check_first_run'),
    selectDirectory: () => ipcRenderer.invoke('select_directory'),
    finishOnboarding: (data) => ipcRenderer.invoke('finish_onboarding', data),
    setAppLocale: (locale) => ipcRenderer.invoke('set_app_locale', locale),
    openCharacterWindow: (characterType, editProfile) => ipcRenderer.invoke('open_character_window', characterType, editProfile),
    openProfileWindow: () => ipcRenderer.invoke('open_profile_window'),
    resetOnboarding: () => ipcRenderer.invoke('reset_onboarding'),
    getProfiles: () => ipcRenderer.invoke('get_profiles'),
    updateProfile: (data) => ipcRenderer.invoke('update_profile', data),
    deleteProfile: (profileId) => ipcRenderer.invoke('delete_profile', profileId),
    closeCharacterWindow: () => ipcRenderer.send('close_character_window'),
    createCharacter: (data) => ipcRenderer.send('create_character', data),
    microsoftAuth: () => ipcRenderer.invoke('microsoft_auth'),
    onCharacterWindowClosed: (callback) => ipcRenderer.on('character_window_closed', callback),
    onCharacterCreated: (callback) => ipcRenderer.on('character_created', (event, data) => callback(data)),
    onCharacterType: (callback) => ipcRenderer.on('character_type', (event, type) => callback(type)),
    onCharacterEdit: (callback) => ipcRenderer.on('edit_profile', (event, data) => callback(data)),
    getWardrobe: () => ipcRenderer.invoke('get_wardrobe'),
    addWardrobeItem: (item) => ipcRenderer.invoke('add_wardrobe_item', item),
    deleteWardrobeItem: (itemId, type) => ipcRenderer.invoke('delete_wardrobe_item', itemId, type),
    updateWardrobeItem: (item) => ipcRenderer.invoke('update_wardrobe_item', item),
    selectSkinFile: () => ipcRenderer.invoke('select_skin_file'),
    selectCapeFile: () => ipcRenderer.invoke('select_cape_file'),
    getSystemUsername: () => ipcRenderer.invoke('get_system_username'),
    getDisplayName: () => ipcRenderer.invoke('get_display_name'),
    setDisplayName: (name) => ipcRenderer.invoke('set_display_name', name),
    getInstallPath: () => ipcRenderer.invoke('get_install_path'),
    setInstallPath: (path) => ipcRenderer.invoke('set_install_path', path),
    selectInstallDirectory: () => ipcRenderer.invoke('select_install_directory'),
    getMinecraftVersions: () => ipcRenderer.invoke('get_minecraft_versions'),
    getVersionDetails: (versionId) => ipcRenderer.invoke('get_version_details', versionId),
    startDownload: (versionId, options) => ipcRenderer.invoke('start_download', versionId, options),
    pauseDownload: () => ipcRenderer.invoke('pause_download'),
    resumeDownload: () => ipcRenderer.invoke('resume_download'),
    cancelDownload: () => ipcRenderer.invoke('cancel_download'),
    onDownloadProgress: (callback) => ipcRenderer.on('download_progress', (event, data) => callback(data)),
    getDownloadSource: () => ipcRenderer.invoke('get_download_source'),
    setDownloadSource: (source) => ipcRenderer.invoke('set_download_source', source),
    getInstalledVersions: () => ipcRenderer.invoke('get_installed_versions'),
    deleteVersion: (versionId) => ipcRenderer.invoke('delete_version', versionId),
    copyVersion: (sourceVersionId, newVersionId) => ipcRenderer.invoke('copy_version', sourceVersionId, newVersionId),
    renameVersion: (oldVersionId, newVersionId) => ipcRenderer.invoke('rename_version', oldVersionId, newVersionId),
    getDownloadSettings: () => ipcRenderer.invoke('get_download_settings'),
    setDownloadSettings: (settings) => ipcRenderer.invoke('set_download_settings', settings),
    getMusicSettings: () => ipcRenderer.invoke('get_music_settings'),
    setMusicSettings: (settings) => ipcRenderer.invoke('set_music_settings', settings),
    setMusicVolume: (volume) => ipcRenderer.invoke('set_music_volume', volume),
    toggleMusic: () => ipcRenderer.invoke('toggle_music'),
    skipToNextMusic: () => ipcRenderer.invoke('skip_to_next_music'),
    onMusicEnded: (callback) => ipcRenderer.on('music_ended', callback),
    readAudioFile: (filePath) => ipcRenderer.invoke('read_audio_file', filePath),
    requestPlayMusic: () => ipcRenderer.invoke('request_play_music')
});